artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion

  raw_dir: artifacts/data_ingestion/raw

  extracted_dir: artifacts/data_ingestion/extracted

  processed_dir: artifacts/data_ingestion/processed

  image_zip: artifacts/data_ingestion/raw/Flickr8k_Dataset.zip

  text_zip: artifacts/data_ingestion/raw/Flickr8k_text.zip

  images_dir: artifacts/data_ingestion/extracted/Flickr8k_Dataset

  captions_file: artifacts/data_ingestion/extracted/Flickr8k.token.txt

  train_split: artifacts/data_ingestion/extracted/Flickr_8k.trainImages.txt

  validation_split: artifacts/data_ingestion/extracted/Flickr_8k.devImages.txt

  test_split: artifacts/data_ingestion/extracted/Flickr_8k.testImages.txt

model_trainer:
  root_dir: artifacts/model_trainer
  trained_model_path: artifacts/model_trainer/image_caption_model.keras

prediction:
  upload_dir: uploads

data_validation:
  root_dir: artifacts/data_validation

  images_dir: artifacts/data_ingestion/extracted/Flicker8k_Dataset

  captions_file: artifacts/data_ingestion/extracted/Flickr8k.token.txt

  train_split: artifacts/data_ingestion/extracted/Flickr_8k.trainImages.txt

  validation_split: artifacts/data_ingestion/extracted/Flickr_8k.devImages.txt

  test_split: artifacts/data_ingestion/extracted/Flickr_8k.testImages.txt

  status_file: artifacts/data_validation/status.txt

caption_parser:
  root_dir: artifacts/caption_parser

  captions_file: artifacts/data_ingestion/extracted/Flickr8k.token.txt

  output_file: artifacts/caption_parser/captions.csv

caption_cleaner:
  root_dir: artifacts/caption_cleaner

  input_file: artifacts/caption_parser/captions.csv

  output_file: artifacts/caption_cleaner/cleaned_captions.csv

dataset_splitter:
  root_dir: artifacts/dataset_splitter

  captions_file: artifacts/caption_cleaner/cleaned_captions.csv

  train_images: artifacts/data_ingestion/extracted/Flickr_8k.trainImages.txt

  validation_images: artifacts/data_ingestion/extracted/Flickr_8k.devImages.txt

  test_images: artifacts/data_ingestion/extracted/Flickr_8k.testImages.txt

  train_output: artifacts/dataset_splitter/train.csv

  validation_output: artifacts/dataset_splitter/validation.csv

  test_output: artifacts/dataset_splitter/test.csv